### ISSUE TITLE
Site Editor question

### ISSUE THREAD

**Issue by pavliukpetro** [WordPress/gutenberg-starter-theme#110]
Hello,
does it support the Site editor?
I am clicked Appearence -> Editor and it shows the blank page

**Comment by bph** [comment]
Ohh. Thanks for your comment. There is definitely a need to update this repo's read me file to make clear that it only covers blocks in the post-editor context (among other needed updates.)

The newer plugin  create-block-theme should get you started with a theme that works with the site editor. 
https://wordpress.org/plugins/create-block-theme/

**Comment by pavliukpetro** [comment]
> Ohh. Thanks for your comment. There is definitely a need to update this repo's read me file to make clear that it only covers blocks in the post-editor context (among other needed updates.)
> 
> The newer plugin create-block-theme should get you started with a theme that works with the site editor. https://wordpress.org/plugins/create-block-theme/

Thank a lot for your answer!
