### ISSUE TITLE
Blockquotes need to be styled

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg-starter-theme#12]
![image](https://user-images.githubusercontent.com/2846578/29092923-fb04c0d4-7c55-11e7-853e-47ec58288596.png)

Should be styled like Gutenberg: 

![image](https://user-images.githubusercontent.com/2846578/29092951-116c533c-7c56-11e7-8aff-69c3cddff9d2.png)

**Comment by karmatosed** [comment]
Closing as now styled.

**Comment by MihaiCraciun** [comment]
this wasn't fixed.
there's no reference in the css for `blockquote` element styling

LE: The sample page that WordPress comes with has a single element (classic) and the blockquote from that element doesn't get the styling 
![image](https://user-images.githubusercontent.com/7666090/56430616-858eee80-62cf-11e9-9d70-c5e9c33a3329.png)

Adding a separate blockquote element or even copy pasting the content from the classic element in a new block fixes this.
