### ISSUE TITLE
Two columns gallery doesn't match with other elements width

### ISSUE THREAD

**Issue by Axinet** [WordPress/gutenberg-starter-theme#18]
In editor 2 columns gallery has the exact same width as image inserted alone:
![gallery-vs-image-editor](https://user-images.githubusercontent.com/393549/31453423-6d413630-aeb2-11e7-9a46-64db1ca4bad5.PNG)

On frontend page view there is a visible width difference on the right side (marked with the red box):
![gallery-vs-image](https://user-images.githubusercontent.com/393549/31453539-ca9b6544-aeb2-11e7-95f3-9c9668479002.PNG)

**Comment by karmatosed** [comment]
Do you get the same issue with just the twenty seventeen or any default theme? I'm thinking this isn't the theme.

**Comment by Axinet** [comment]
Yes, twenty seventeen has the exact same issue on frontend view. You are right - it is related to css selector `.wp-block-gallery .blocks-gallery-image` from /wp-content/plugins/gutenberg/blocks/build/style.css
