### ISSUE TITLE
Gutenberg Demo broken

### ISSUE THREAD

**Issue by obenland** [WordPress/gutenberg-starter-theme#31]
Gutenberg's demo post doesn't get displayed as it should, I assume some recent changes broke it?

The custom font is missing, an image and the video is left aligned, as is a button where you can't read the text

**Comment by mbaiti** [comment]
same here!

**Comment by karmatosed** [comment]
I think the latest changes fix this but please let me know if not the case.

**Comment by mbaiti** [comment]
Downloaded the latest release and it is not fixed. please reopen.
