### ISSUE TITLE
h5 and h6 span full width

### ISSUE THREAD

**Issue by billerickson** [WordPress/gutenberg-starter-theme#32]
![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/2H0y2x123M123I3v3o18/Screen%20Shot%202018-01-19%20at%203.34.09%20PM.png?X-CloudApp-Visitor-Id=095a13821a9a7633d8999bdb4bf2b94a&v=e0546efd)

The Heading block popup toolbar only has h2-h4, but the settings panel includes h1-h6. And even if the [settings panel removes h5 and h6](https://github.com/WordPress/gutenberg/issues/2244), it's still valid HTML markup and should be styled appropriately.

**Comment by easilyamused** [comment]
I think pull #33 should fix this.

**Comment by karmatosed** [comment]
This does seem fixed now, lets close.
