### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by mbaiti** [WordPress/gutenberg-starter-theme#44]
As Issue #31 was closed, i open this issue:

The demo is still broken. I've installed the latest WP Version, latest gutenberg plugin and the latest gutenberg-starter-theme. Still the same problems. Font ist not loading correctly, i think also some CSS bugs.

https://github.com/WordPress/gutenberg-starter-theme/issues/31

**Comment by kjellr** [comment]
@mbaiti, would you mind checking out the demo post now? The font + css issues should be fixed with the latest batch of commits.

**Comment by mbaiti** [comment]
Looks way better! Thanks @kjellr
