### ISSUE TITLE
Resized image Does not display

### ISSUE THREAD

**Issue by jeffrainey** [WordPress/gutenberg-starter-theme#45]
Versions: WP 4.9.6 | Gutenberg 2.9.2 | GST 1.0.0 | Chrome 66.0.3359.181

This may be a known issue, but the image block is not rendering. Here is my homepage:
![image](https://user-images.githubusercontent.com/365987/40735942-9169273a-640a-11e8-9cac-fe3f3c6dc840.png)

Here is the backend:
![image](https://user-images.githubusercontent.com/365987/40735901-74aca950-640a-11e8-82a5-05c1459a87c7.png)

In playing with this I figured out how to recreate the issue.

1. Add an image block and upload an image or choose from library.
2. Drag one of the corners to resize the image. Any size adjustment seems to cause the issue.
3. Update and view source. The image is there, but something is setting the size to 0x0. It does not appear to be the CSS that is doing this.

![image](https://user-images.githubusercontent.com/365987/40735814-2b15eeaa-640a-11e8-89a2-33e4f312074e.png)

I will try to debug this later if I find time, but work is crazy the next couple of weeks...

**Comment by jeffrainey** [comment]
Actually, it is totally the CSS. Unchecking these styles displays the image.
![image](https://user-images.githubusercontent.com/365987/40736132-2420de7e-640b-11e8-8208-39dfac767698.png)

**Comment by kjellr** [comment]
Good find, @jeffrainey! It looks like the `min-content` property value of the `wp-image-block` container is conflicting with the `100%` width of the image itself. I'm pretty sure #54 should get things working again.

**Comment by jeffrainey** [comment]
Looks great, thanks @kjellr!
