### ISSUE TITLE
Featured Images don't appear, even though the theme supports them. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg-starter-theme#51]
This is a fairly straightforward issue, but it requires a bit of discussion. The theme [declares support for featured images](https://github.com/WordPress/gutenberg-starter-theme/blob/5d9d9239c40add1cbb33839e151cef05d5c441ba/functions.php#L43), but does not display them on the front end. I used this theme for a test recently, and this point caused some confusion.  

Should we: 

**1. Remove theme support for featured images?**
This makes sense if we're committed to having the front end look just like the backend editor. But I do think it's helpful for people too see where featured images live inside of Gutenberg. 

**2. Keep it, and add featured images on the front end.**
This solves for potential confusion, but it also means that posts on the front end won't look 100% like they do inside of the editor. 

**3. Keep things the way they are.**

Any thoughts?

**Comment by zgordon** [comment]
This is slightly unrelated but the same is true for custom header image. I don't think it's used on the frontend, just the custom logo. But theme does support it.

**Comment by kjellr** [comment]
Good catch! My gut says to remove theme support for both of those (for now at least) and keep the focus purely on Gutenberg-related elements, but I'm interested in what everyone else thinks.

**Comment by jeffrainey** [comment]
The main issue that comes to mind ( with removing the featured image ) is losing it when displaying post archives, in search, category and taxonomy displays. But, I just found this theme a couple of weeks ago and do not know the overall goals for the theme.

**Comment by warrengroom** [comment]
One of the first things I did when testing this theme was to add featured images, so the fact that they're supported was nice. That said, I love that they're not displaying by default and that the focus is on Gutenberg-related elements.

My instinct is that if you stray from pure Gutenberg elements with anything additional, featured images is the natural addition. If it potentially opens up a can of worms with people requesting other non-Gutenberg items, then bin the featured images and go pure-Gut.

**Comment by Xarcell** [comment]
How can I get featured images to work then? Or to display rather.

**Comment by richtabor** [comment]
I'd say having featured image support is important for post archives, though for the actual singular post view - not so much. Gutenberg should be handling the entire presentation of the singular post view.

**Comment by zgordon** [comment]
Agreed with Rich that it is helpful for archives but shouldn't be in single templates.

**Comment by kjellr** [comment]
That seems like a reasonable compromise to me. I'll get a PR going next week, unless someone else beats me to it. 👍
