### ISSUE TITLE
Block color palette names should be translatable

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg-starter-theme#69]
With the addition of slugs, we can now have translatable names for each color defined in the `editor-color-palette`.

[Here's](https://github.com/WordPress/gutenberg/blob/master/docs/extensibility/theme-support.md#block-color-palettes) the info on color palettes from the Gutenberg repo.

**Comment by kjellr** [comment]
Closing via #70. Thanks again, @richtabor!
