### ISSUE TITLE
Add contextual color classes for editor color palette colors

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg-starter-theme#71]
**Describe the bug**
Colors are not being appropriately rendered on the front-end of core blocks, as they're not defined within the theme's styles. 

**Expected behavior** 
The colors (background/color) are applied on the front-end, with the use of proper contextual color classes. 

**Screenshots**
<img width="1447" alt="screen shot 2018-07-25 at 10 01 04 am" src="https://user-images.githubusercontent.com/1813435/43205572-af63604e-8ff1-11e8-8973-7a764f499b88.png">
<img width="758" alt="screen shot 2018-07-25 at 9 59 24 am" src="https://user-images.githubusercontent.com/1813435/43205463-6ddc342a-8ff1-11e8-816f-db3e6b380c46.png">

**Additional context**
From the Gutenberg doc on the editor color palette ([link](https://github.com/WordPress/gutenberg/blob/master/docs/extensibility/theme-support.md#block-color-palettes)): 

Themes are responsible for creating the classes that apply the colors in different contexts. Core blocks use "color" and "background-color" contexts. So to correctly apply "strong magenta" to all contexts of core blocks a theme should implement the following classes:

```
.has-strong-magenta-background-color {
	background-color: #313131;
}

.has-strong-magenta-color {
	color: #f78da7;
}
```

**Comment by kjellr** [comment]
Closed via #72.
